/** Direction L'Itinéraire d'Or: contenu bilingue précis, calme et sans promesse invérifiable. */
export type Language = "fr" | "en";
export type Localized = Record<Language, string>;
export const tr = (value: Localized, language: Language) => value[language];
export type ServiceSlug = "visa" | "billets" | "hotels" | "packages" | "assurance" | "conciergerie" | "coaching";
export type TravelService = { slug: ServiceSlug; number: string; name: Localized; eyebrow: Localized; summary: Localized; longDescription: Localized; deliverables: Localized[]; image?: string };

export const assets = { logo: "https://trusttravel-x42xvjah.manus.space/manus-storage/trust-elite-official-logo-clean_e147d9e4.png", mark: "https://trusttravel-x42xvjah.manus.space/manus-storage/trust-elite-mark_6497b569.png", hero: "https://trusttravel-x42xvjah.manus.space/manus-storage/trust-elite-hero_94b5c17b.webp", visa: "https://trusttravel-x42xvjah.manus.space/manus-storage/trust-elite-visa_9d69f84b.webp", hotel: "https://trusttravel-x42xvjah.manus.space/manus-storage/trust-elite-hotel_4af6cb81.webp", coaching: "https://trusttravel-x42xvjah.manus.space/manus-storage/trust-elite-coaching_6f058e5e.webp", globe: "https://trusttravel-x42xvjah.manus.space/manus-storage/trust-elite-globe_64cbc911.webp", wing: "https://trusttravel-x42xvjah.manus.space/manus-storage/trust-elite-wing_7d090577.webp", flightRoute: "https://trusttravel-x42xvjah.manus.space/manus-storage/trust-elite-flight-route_8b65fee6.webp", douala: "https://trusttravel-x42xvjah.manus.space/manus-storage/trust-elite-douala_8d2b4c8c.webp" };
export const contact = { email: "contact@trustelitetravels.com", phones: [{ display: "+237 655 44 93 35", wa: "237655449335" }, { display: "+237 654 99 77 30", wa: "237654997730" }], city: { fr: "Douala–Makepe, face CNPS", en: "Douala–Makepe, opposite CNPS" } satisfies Localized };

export const services: TravelService[] = [
  { slug:"billets", number:"01", name:{fr:"Billets d’avion & transport",en:"Air tickets & transport"}, eyebrow:{fr:"National & international",en:"National & international"}, summary:{fr:"Des options de trajet adaptées pour vos déplacements nationaux et internationaux.",en:"Tailored route options for your national and international travel."}, longDescription:{fr:"Nous vous aidons à organiser votre transport et à choisir un itinéraire cohérent avec votre calendrier et votre projet.",en:"We help organize your transport and select a route that suits your schedule and travel plan."}, deliverables:[{fr:"Recherche d’itinéraires",en:"Route search"},{fr:"Comparaison des options",en:"Options comparison"},{fr:"Préparation au départ",en:"Departure preparation"}] },
  { slug:"hotels", number:"02", name:{fr:"Réservations d’hôtels",en:"Hotel reservations"}, eyebrow:{fr:"Confortables & sécurisées",en:"Comfortable & secure"}, summary:{fr:"Des hébergements sélectionnés pour vous aider à préparer un séjour confortable et serein.",en:"Selected accommodation to help you prepare a comfortable and relaxed stay."}, longDescription:{fr:"Nous vous présentons des options d’hébergement adaptées à votre destination, à la durée de votre séjour et à vos priorités.",en:"We present accommodation options that fit your destination, length of stay and priorities."}, deliverables:[{fr:"Sélection selon le séjour",en:"Stay-based selection"},{fr:"Présentation des options",en:"Options overview"},{fr:"Confirmation des informations",en:"Information confirmation"}], image:assets.hotel },
  { slug:"visa", number:"03", name:{fr:"Assistance visa",en:"Visa assistance"}, eyebrow:{fr:"Dossier & orientation",en:"File preparation & guidance"}, summary:{fr:"Un accompagnement pour vos visas Schengen, France, Belgique et autres destinations selon votre projet.",en:"Guidance for Schengen, France, Belgium and other destination visa files according to your plan."}, longDescription:{fr:"Préparez votre démarche avec méthode. Nous vous aidons à organiser les informations nécessaires et à comprendre les étapes à prévoir.",en:"Prepare your process methodically. We help you organize the necessary information and understand the expected steps."}, deliverables:[{fr:"Analyse initiale du besoin",en:"Initial needs review"},{fr:"Liste de pièces à préparer",en:"Document checklist"},{fr:"Suivi des prochaines étapes",en:"Next-step guidance"}], image:assets.visa },
  { slug:"packages", number:"04", name:{fr:"Voyages & packages",en:"Travel & packages"}, eyebrow:{fr:"Séjours sur mesure",en:"Tailored stays"}, summary:{fr:"Des séjours sur mesure, circuits touristiques et offres spéciales selon vos envies.",en:"Custom stays, tourism circuits and special offers aligned with your plans."}, longDescription:{fr:"Nous vous orientons vers des propositions de séjour qui articulent destination, transport, hébergement et rythme de voyage.",en:"We guide you toward stay proposals that bring together destination, transport, accommodation and travel pace."}, deliverables:[{fr:"Écoute du projet",en:"Plan discovery"},{fr:"Proposition de séjour",en:"Stay proposal"},{fr:"Orientation pratique",en:"Practical guidance"}] },
  { slug:"assurance", number:"05", name:{fr:"Assurance voyage",en:"Travel insurance"}, eyebrow:{fr:"Voyagez en toute sécurité",en:"Travel with confidence"}, summary:{fr:"Une orientation pour choisir une couverture adaptée à vos besoins, avec des informations faciles à suivre.",en:"Guidance to choose cover that suits your needs, with clear and practical information."}, longDescription:{fr:"La couverture voyage fait partie d’une préparation rigoureuse. Nous vous aidons à identifier les éléments utiles à votre demande.",en:"Travel cover is part of careful preparation. We help identify the elements useful to your request."}, deliverables:[{fr:"Orientation selon le projet",en:"Guidance based on your plan"},{fr:"Lecture des éléments essentiels",en:"Review of key elements"},{fr:"Intégration au dossier",en:"Integration into your file"}] },
  { slug:"conciergerie", number:"06", name:{fr:"Conciergerie & services",en:"Concierge & services"}, eyebrow:{fr:"Un service premium",en:"A premium service"}, summary:{fr:"Des services premium et un accompagnement personnalisé avant, pendant et après votre voyage.",en:"Premium services and personalized support before, during and after your journey."}, longDescription:{fr:"Lorsque votre projet demande davantage d’attention, nous vous aidons à anticiper les détails et à organiser les étapes complémentaires.",en:"When your plan requires added attention, we help anticipate details and organize the complementary steps."}, deliverables:[{fr:"Écoute personnalisée",en:"Personalized listening"},{fr:"Coordination des besoins",en:"Needs coordination"},{fr:"Suivi du parcours",en:"Journey follow-up"}] },
  { slug:"coaching", number:"07", name:{fr:"Accompagnement PNC – hôtesses de l’air & stewards",en:"Cabin crew coaching"}, eyebrow:{fr:"Hôtesses de l’air & stewards",en:"Flight attendants & stewards"}, summary:{fr:"Un accompagnement pour préparer votre parcours vers les métiers d’hôtesse de l’air et de steward.",en:"Guidance to prepare your path toward flight attendant and steward careers."}, longDescription:{fr:"Nous vous accompagnons dans votre préparation, votre présentation et votre compréhension des exigences d’un parcours vers les métiers de cabine.",en:"We support your preparation, presentation and understanding of requirements for a path toward cabin careers."}, deliverables:[{fr:"Clarification du projet professionnel",en:"Career-plan clarification"},{fr:"Préparation à la présentation",en:"Presentation preparation"},{fr:"Orientation sur le parcours",en:"Pathway guidance"}], image:assets.coaching },
];

export const ui = { fr:{nav:{home:"Accueil",services:"Services",about:"À propos",contact:"Contact"},contact:"Nous contacter",request:"Faire une demande",discover:"Découvrir le service",allServices:"Voir tous les services",language:"EN",location:"Notre adresse",close:"Fermer le menu",menu:"Ouvrir le menu",footer:"Un accompagnement de voyage clair, attentif et sur mesure.",legal:"Les informations de contact et les textes légaux seront finalisés avant publication."}, en:{nav:{home:"Home",services:"Services",about:"About",contact:"Contact"},contact:"Contact us",request:"Make an enquiry",discover:"Explore service",allServices:"View all services",language:"FR",location:"Our address",close:"Close menu",menu:"Open menu",footer:"Clear, attentive and tailored travel support.",legal:"Contact information and legal content will be finalized before publication."} } as const;
