"use client";

import { ArrowUpRight, Mail, MapPin, MessageCircle, Phone } from "lucide-react";
import { RequestStepper } from "@/components/RequestStepper";
import { contact, whatsappHref } from "@/lib/content";
import { useLanguage } from "@/contexts/LanguageContext";

export default function Contact() {
  const { language } = useLanguage();
  const isFr = language === "fr";
  return <main id="main-content">
    <section className="contact-hero section-shell"><div className="section-marker"><span>01</span><span>{isFr ? "Prendre contact" : "Get in touch"}</span></div><div className="contact-heading"><h1>{isFr ? <>Votre prochaine étape,<br /><em>en quelques questions.</em></> : <>Your next step,<br /><em>in a few questions.</em></>}</h1><p>{isFr ? "Décrivez simplement votre besoin. Ce formulaire de devis rassemble votre destination, vos dates, votre nombre de voyageurs et vos coordonnées pour nous donner le bon point de départ." : "Simply describe what you need. This quote form gathers your destination, dates, traveler count and contact details to give us the right starting point."}</p></div></section>
    <section className="contact-area"><div className="section-shell contact-grid"><RequestStepper /><aside className="contact-aside"><p className="service-eyebrow">{isFr ? "Nous joindre directement" : "Reach us directly"}</p><div className="contact-item"><MessageCircle size={19} /><div><span>WhatsApp</span>{contact.phones.map(phone => <a key={phone.wa} href={whatsappHref(phone.wa, language)} target="_blank" rel="noreferrer">{phone.display}</a>)}</div></div><div className="contact-item"><Mail size={19} /><div><span>E-mail</span><a href={`mailto:${contact.email}`}>{contact.email}</a></div></div><div className="contact-item"><Phone size={19} /><div><span>{isFr ? "Téléphone" : "Phone"}</span><a href={`tel:+${contact.phones[0].wa}`}>{contact.phones[0].display}</a></div></div><div className="contact-item"><MapPin size={19} /><div><span>{isFr ? "Base" : "Base"}</span><strong>{contact.city[language]}</strong></div></div><p className="aside-note">{isFr ? "L’adresse e-mail utilisée ici est notre contact professionnel pour recevoir et traiter votre demande." : "This professional email is used to receive and process your request."}</p><a className="contact-map-link" href="https://www.google.com/maps/search/?api=1&query=Makepe+CNPS+Douala" target="_blank" rel="noreferrer"><ArrowUpRight size={16} aria-hidden="true" />{isFr ? "Ouvrir l’itinéraire" : "Open directions"}</a></aside></div></section>
    <section className="contact-map-section section-shell"><div className="contact-map-heading"><p className="service-eyebrow">{isFr ? "Nous trouver" : "Find us"}</p><h2>{isFr ? <>Un contact direct<br /><em>à Douala.</em></> : <>A direct contact<br /><em>in Douala.</em></>}</h2><p>{isFr ? "Situé à Douala–Makepe, face CNPS. Consultez la carte avant votre passage ou écrivez-nous pour préparer votre venue." : "Located in Douala–Makepe, opposite CNPS. Check the map before visiting or write to prepare your arrival."}</p></div><div className="contact-map-frame"><iframe title={isFr ? "Carte de Trust Elite Travel à Douala Makepe" : "Trust Elite Travel map in Douala Makepe"} src="https://www.google.com/maps?q=Makepe%20CNPS%20Douala&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /><div className="contact-map-fallback"><MapPin size={24} aria-hidden="true" /><strong>Douala–Makepe</strong><span>{isFr ? "Face CNPS" : "Opposite CNPS"}</span><a href="https://www.google.com/maps/search/?api=1&query=Makepe+CNPS+Douala" target="_blank" rel="noreferrer">{isFr ? "Ouvrir dans Maps" : "Open in Maps"}<ArrowUpRight size={15} aria-hidden="true" /></a></div></div></section>
  </main>;
}
